name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Define project path and repo URL
            PROJECT_PATH="/home/${{ secrets.SSH_USERNAME }}/fitiagrup4"
            REPO_URL="https://github.com/${{ github.repository }}.git"
            BRANCH="main"

            # Clone repo if it doesn't exist, otherwise navigate into it
            if [ ! -d "$PROJECT_PATH" ]; then
              echo "Cloning repository..."
              git clone $REPO_URL $PROJECT_PATH
              cd $PROJECT_PATH
            else
              echo "Repository exists, pulling latest changes..."
              cd $PROJECT_PATH
              git reset --hard
              git clean -fd
              git pull origin $BRANCH
            fi

            # Create .env file from GitHub Secrets
            echo "Creating .env file..."
            echo "NODE_ENV=${{ secrets.NODE_ENV }}" > .env
            echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
            # The backend also needs the root password to connect initially
            echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
            echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
            echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
            # Las variables VITE_* son cruciales para el build del frontend
            echo "VITE_NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
            # Para producción, la URL de la API debe ser relativa para que Nginx la gestione
            echo "VITE_API_URL=/api" >> .env
            echo "VITE_SOCKET_URL=/" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

            # Stop existing services and remove the database volume to ensure a clean start
            echo "Stopping services and removing old database volume..."
            docker compose -f docker-compose.prod.yml down -v

            # Run docker-compose for production
            echo "Starting docker-compose..."
            docker compose -f docker-compose.prod.yml up --build -d --remove-orphans

            # Clean up unused Docker images
            docker image prune -f
