version: '3.8'

services:
  db_mysql:
    image: mysql:8.0
    container_name: meu_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'projBD'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: meu_phpmyadmin
    restart: always
    ports:
      - "8080:80" 
    environment:
      PMA_HOST: db_mysql 
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: '1234' 
    depends_on:
      - db_mysql 

volumes:
  mysql-data:


