version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fithub_server
    restart: always
    ports:
      - "7001:7001"
    environment:
      - DB_HOST=db_mysql
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=projBD
    depends_on:
      db_mysql:
        condition: service_healthy
    volumes:
      - ./server:/usr/src/app # Monta el código para desarrollo en caliente
      - /usr/src/app/node_modules # No montar node_modules del host

  db_mysql:
    image: mysql:8.0
    container_name: meu_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "projBD"
    ports:
      - "33061:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: fithub_client
    restart: always
    ports:
      - "8081:80" # Accederás a la app en http://localhost:8081
    depends_on:
      - server

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db_mysql
    depends_on:
      - db_mysql

volumes:
  mysql-data:
    # No es necesario definirlo como externo si se crea con este compose
